# Generated by Django 3.2.16 on 2023-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default2.jpg', upload_to='blog_pics'),
        ),
    ]
